/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { WebClient } from './webClient';


export interface AuthSuccessMessage { 
    message?: string;
    jwt: string;
    readonly type: AuthSuccessMessage.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace AuthSuccessMessage {
    export const TypeEnum = {
        AuthSuccessMessage: 'AuthSuccessMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


