/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { SignedContentAuthChallenge } from './signedContentAuthChallenge';
import { JsonNode } from './jsonNode';
import { WebClient } from './webClient';


export interface AuthChallengeResponse { 
    publicKey: JsonNode;
    challenge: SignedContentAuthChallenge;
    username: string;
    readonly type: AuthChallengeResponse.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace AuthChallengeResponse {
    export const TypeEnum = {
        AuthChallengeResponse: 'AuthChallengeResponse'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


