/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthChallenge } from './authChallenge';
import { Server } from './server';
import { WebClient } from './webClient';


export interface AuthChallengeRequest { 
    challenge: AuthChallenge;
    readonly type: AuthChallengeRequest.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace AuthChallengeRequest {
    export const TypeEnum = {
        AuthChallengeRequest: 'AuthChallengeRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


