/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserOnlineDTO } from './userOnlineDTO';
import { UserSimpleDTO } from './userSimpleDTO';
import { MessageBody } from './messageBody';


export interface AuthSuccessMessage extends MessageBody { 
    message?: string;
    jwt: string;
    me: UserSimpleDTO;
    clients: UserOnlineDTO[];
    readonly type: AuthSuccessMessage.TypeEnum;
}
export namespace AuthSuccessMessage {
    export const TypeEnum = {
        AuthSuccessMessage: 'AuthSuccessMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


