/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface ChannelDetailRequest extends MessageBody { 
    requestId?: string;
    channelId?: string;
    readonly type: ChannelDetailRequest.TypeEnum;
}
export namespace ChannelDetailRequest {
    export const TypeEnum = {
        ChannelDetailRequest: 'ChannelDetailRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


