/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface ChannelCreateRequest extends MessageBody { 
    name?: string;
    section?: string;
    readonly type: ChannelCreateRequest.TypeEnum;
}
export namespace ChannelCreateRequest {
    export const TypeEnum = {
        ChannelCreateRequest: 'ChannelCreateRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


