/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface ChannelDeleteEvent extends MessageBody { 
    channelId: string;
    readonly type: ChannelDeleteEvent.TypeEnum;
}
export namespace ChannelDeleteEvent {
    export const TypeEnum = {
        ChannelDeleteEvent: 'ChannelDeleteEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


