/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSimpleDTO } from './userSimpleDTO';


export interface ChannelExtendedDTO { 
    readonly sectionId: string;
    readonly order: number;
    readonly name: string;
    id: string;
    chatId: string;
    users: UserSimpleDTO[];
}

