/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { WebClient } from './webClient';


export interface ChannelDetailRequest { 
    requestId?: string;
    channelId?: string;
    readonly type: ChannelDetailRequest.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace ChannelDetailRequest {
    export const TypeEnum = {
        ChannelDetailRequest: 'ChannelDetailRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


