/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelDTO } from './channelDTO';
import { MessageBody } from './messageBody';


export interface ChannelDetailResponse extends MessageBody { 
    respondsTo: string;
    channel?: ChannelDTO;
    readonly type: ChannelDetailResponse.TypeEnum;
}
export namespace ChannelDetailResponse {
    export const TypeEnum = {
        ChannelDetailResponse: 'ChannelDetailResponse'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


