/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelDTO } from './channelDTO';
import { MessageBody } from './messageBody';


export interface ChannelChangeEvent extends MessageBody { 
    channel: ChannelDTO;
    readonly type: ChannelChangeEvent.TypeEnum;
}
export namespace ChannelChangeEvent {
    export const TypeEnum = {
        ChannelChangeEvent: 'ChannelChangeEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


