/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { ChannelReference } from './channelReference';
import { WebClient } from './webClient';


export interface ChannelDetailResponse { 
    respondsTo: string;
    channel?: ChannelReference;
    readonly type: ChannelDetailResponse.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace ChannelDetailResponse {
    export const TypeEnum = {
        ChannelDetailResponse: 'ChannelDetailResponse'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


