/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChannelDTO { 
    name: string;
    policies: { [key: string]: any; };
    id: string;
    chatId: string;
}

