/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDTO } from './messageDTO';


export interface ChatMessageEvent { 
    chatId: string;
    message: MessageDTO;
    readonly type: ChatMessageEvent.TypeEnum;
}
export namespace ChatMessageEvent {
    export const TypeEnum = {
        ChatMessageEvent: 'ChatMessageEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


