/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSimpleDTO } from './userSimpleDTO';
import { MessageBody } from './messageBody';


export interface ClientServerJoinEvent extends MessageBody { 
    user: UserSimpleDTO;
    readonly type: ClientServerJoinEvent.TypeEnum;
}
export namespace ClientServerJoinEvent {
    export const TypeEnum = {
        ClientServerJoinEvent: 'ClientServerJoinEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


