/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSimpleDTO } from './userSimpleDTO';
import { MessageBody } from './messageBody';


export interface ClientChannelJoinEvent extends MessageBody { 
    user: UserSimpleDTO;
    channelId?: string;
    readonly type: ClientChannelJoinEvent.TypeEnum;
}
export namespace ClientChannelJoinEvent {
    export const TypeEnum = {
        ClientChannelJoinEvent: 'ClientChannelJoinEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


