/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface ClientChannelChangeRequest extends MessageBody { 
    channelId?: string;
    readonly type: ClientChannelChangeRequest.TypeEnum;
}
export namespace ClientChannelChangeRequest {
    export const TypeEnum = {
        ClientChannelChangeRequest: 'ClientChannelChangeRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


