/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { UserReference } from './userReference';
import { WebClient } from './webClient';


export interface ClientChannelLeaveMessage { 
    user: UserReference;
    readonly type: ClientChannelLeaveMessage.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace ClientChannelLeaveMessage {
    export const TypeEnum = {
        ClientChannelLeaveMessage: 'ClientChannelLeaveMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


