/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicUserDTO } from './publicUserDTO';
import { MessageBody } from './messageBody';


export interface ClientChannelLeaveMessage extends MessageBody { 
    user: PublicUserDTO;
    readonly type: ClientChannelLeaveMessage.TypeEnum;
}
export namespace ClientChannelLeaveMessage {
    export const TypeEnum = {
        ClientChannelLeaveMessage: 'ClientChannelLeaveMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


