/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { UserReference } from './userReference';
import { WebClient } from './webClient';


export interface ClientChannelJoinMessage { 
    user: UserReference;
    channelId?: string;
    readonly type: ClientChannelJoinMessage.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace ClientChannelJoinMessage {
    export const TypeEnum = {
        ClientChannelJoinMessage: 'ClientChannelJoinMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


