/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientChannelLeaveEvent { 
    userId: string;
    readonly type: ClientChannelLeaveEvent.TypeEnum;
}
export namespace ClientChannelLeaveEvent {
    export const TypeEnum = {
        ClientChannelLeaveEvent: 'ClientChannelLeaveEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


