/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientChannelJoinEvent { 
    userId: string;
    channelId: string;
    readonly type: ClientChannelJoinEvent.TypeEnum;
}
export namespace ClientChannelJoinEvent {
    export const TypeEnum = {
        ClientChannelJoinEvent: 'ClientChannelJoinEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


