/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface ClientChannelLeaveRequest extends MessageBody { 
    readonly type: ClientChannelLeaveRequest.TypeEnum;
}
export namespace ClientChannelLeaveRequest {
    export const TypeEnum = {
        ClientChannelLeaveRequest: 'ClientChannelLeaveRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


