/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSimpleDTO } from './userSimpleDTO';
import { MessageBody } from './messageBody';


export interface ClientKickEvent extends MessageBody { 
    user: UserSimpleDTO;
    reason: ClientKickEvent.ReasonEnum;
    message?: string;
    readonly type: ClientKickEvent.TypeEnum;
}
export namespace ClientKickEvent {
    export const ReasonEnum = {
        AlreadyConnected: 'ALREADY_CONNECTED',
        UnauthorizedRequest: 'UNAUTHORIZED_REQUEST',
        InternalError: 'INTERNAL_ERROR',
        Banned: 'BANNED',
        Other: 'OTHER'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
    export const TypeEnum = {
        ClientKickEvent: 'ClientKickEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


