/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicUserDTO } from './publicUserDTO';
import { MessageBody } from './messageBody';


export interface ClientChannelJoinMessage extends MessageBody { 
    user: PublicUserDTO;
    channelId?: string;
    readonly type: ClientChannelJoinMessage.TypeEnum;
}
export namespace ClientChannelJoinMessage {
    export const TypeEnum = {
        ClientChannelJoinMessage: 'ClientChannelJoinMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


