/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSimpleDTO } from './userSimpleDTO';
import { MessageBody } from './messageBody';


export interface ClientChangeEvent extends MessageBody { 
    user: UserSimpleDTO;
    readonly type: ClientChangeEvent.TypeEnum;
}
export namespace ClientChangeEvent {
    export const TypeEnum = {
        ClientChangeEvent: 'ClientChangeEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


