/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface ClientChannelJoinRequest extends MessageBody { 
    channelId: string;
    readonly type: ClientChannelJoinRequest.TypeEnum;
}
export namespace ClientChannelJoinRequest {
    export const TypeEnum = {
        ClientChannelJoinRequest: 'ClientChannelJoinRequest'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


