/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyDTO } from './policyDTO';
import { RolePolicyDTO } from './rolePolicyDTO';


/**
 * @type Edit2200Response
 * @export
 */
export type Edit2200Response = PolicyDTO | RolePolicyDTO;

