/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';
import { MessageContentDTO } from './messageContentDTO';


export interface FileMessageContentDTO extends MessageContentDTO { 
    file: FileDTO;
}

