/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileDTO { 
    id?: string;
    filename?: string;
    contentType?: string;
    hashType?: FileDTO.HashTypeEnum;
    created?: string;
}
export namespace FileDTO {
    export const HashTypeEnum = {
        Sha256: 'SHA_256'
    } as const;
    export type HashTypeEnum = typeof HashTypeEnum[keyof typeof HashTypeEnum];
}


