/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';
import { PermissionDTO } from './permissionDTO';


export interface GroupDTO { 
    readonly id: string;
    name: string;
    description?: string;
    icon?: FileDTO;
    inheritsFrom?: GroupDTO[];
    priority: number;
    defaultForNewUsers: boolean;
    permissions?: PermissionDTO[];
    label: boolean;
}

