/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDTO } from './messageDTO';
import { MessageBody } from './messageBody';


export interface IncomeMessageEvent extends MessageBody { 
    chatId: string;
    message: MessageDTO;
    readonly type: IncomeMessageEvent.TypeEnum;
}
export namespace IncomeMessageEvent {
    export const TypeEnum = {
        IncomeMessageEvent: 'IncomeMessageEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


