/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { WebClient } from './webClient';


export interface JwtTokenMessage { 
    token: string;
    readonly type: JwtTokenMessage.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace JwtTokenMessage {
    export const TypeEnum = {
        JwtTokenMessage: 'JwtTokenMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


