/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface JwtTokenMessage extends MessageBody { 
    jwt: string;
    readonly type: JwtTokenMessage.TypeEnum;
}
export namespace JwtTokenMessage {
    export const TypeEnum = {
        JwtTokenMessage: 'JwtTokenMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


