/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface JwtTokenEvent extends MessageBody { 
    jwt: string;
    readonly type: JwtTokenEvent.TypeEnum;
}
export namespace JwtTokenEvent {
    export const TypeEnum = {
        JwtTokenEvent: 'JwtTokenEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


