/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface KickedEvent extends MessageBody { 
    reason: KickedEvent.ReasonEnum;
    message?: string;
    readonly type: KickedEvent.TypeEnum;
}
export namespace KickedEvent {
    export const ReasonEnum = {
        AlreadyConnected: 'ALREADY_CONNECTED',
        UnauthorizedRequest: 'UNAUTHORIZED_REQUEST',
        InternalError: 'INTERNAL_ERROR',
        Banned: 'BANNED',
        Other: 'OTHER'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
    export const TypeEnum = {
        KickedEvent: 'KickedEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


