/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface KickMessage extends MessageBody { 
    reason?: KickMessage.ReasonEnum;
    readonly type: KickMessage.TypeEnum;
}
export namespace KickMessage {
    export const ReasonEnum = {
        AlreadyConnected: 'ALREADY_CONNECTED',
        UnauthorizedRequest: 'UNAUTHORIZED_REQUEST',
        InternalError: 'INTERNAL_ERROR'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
    export const TypeEnum = {
        KickMessage: 'KickMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


