/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageContentDTO } from './messageContentDTO';


export interface MarkdownMessageContentDTO extends MessageContentDTO { 
    text: string;
}
export namespace MarkdownMessageContentDTO {
}


