/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Edit1Request } from './edit1Request';
import { UserSimpleDTO } from './userSimpleDTO';


export interface MessageDTO { 
    id: string;
    timestamp: string;
    user: UserSimpleDTO;
    content?: Array<Edit1Request>;
}

