/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A list of all message types
 */
export const MessageTypes = {
    ClientChannelChangeRequest: 'ClientChannelChangeRequest',
    IceServerMessage: 'IceServerMessage',
    AuthChallengeRequest: 'AuthChallengeRequest',
    JwtTokenMessage: 'JwtTokenMessage',
    IncomeMessageEvent: 'IncomeMessageEvent',
    PeerAnswerForward: 'PeerAnswerForward',
    PeerOffer: 'PeerOffer',
    ChannelDetailRequest: 'ChannelDetailRequest',
    AuthChallengeResponse: 'AuthChallengeResponse',
    AuthSuccessMessage: 'AuthSuccessMessage',
    ClientChannelLeaveMessage: 'ClientChannelLeaveMessage',
    PeerOfferForward: 'PeerOfferForward',
    ChannelDetailResponse: 'ChannelDetailResponse',
    KickMessage: 'KickMessage',
    PeerAnswer: 'PeerAnswer',
    ClientChannelJoinMessage: 'ClientChannelJoinMessage',
    ServerTreeChangeMessage: 'ServerTreeChangeMessage'
} as const;
export type MessageTypes = typeof MessageTypes[keyof typeof MessageTypes];

