/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A list of all message types
 */
export const MessageTypes = {
    ChatMessageEvent: 'ChatMessageEvent',
    PeerOfferForward: 'PeerOfferForward',
    PeerAnswerForward: 'PeerAnswerForward',
    ClientChannelLeaveEvent: 'ClientChannelLeaveEvent',
    ServerChangeEvent: 'ServerChangeEvent',
    ChannelChangeEvent: 'ChannelChangeEvent',
    ServerTreeChangeMessage: 'ServerTreeChangeMessage',
    ClientServerLeaveEvent: 'ClientServerLeaveEvent',
    ClientChannelJoinRequest: 'ClientChannelJoinRequest',
    PeerAnswer: 'PeerAnswer',
    SectionCreateEvent: 'SectionCreateEvent',
    SectionMoveEvent: 'SectionMoveEvent',
    SectionDeleteEvent: 'SectionDeleteEvent',
    ClientChangeEvent: 'ClientChangeEvent',
    AuthSuccessMessage: 'AuthSuccessMessage',
    IceServerMessage: 'IceServerMessage',
    PeerOffer: 'PeerOffer',
    AuthChallengeResponse: 'AuthChallengeResponse',
    ChannelDeleteEvent: 'ChannelDeleteEvent',
    ClientKickEvent: 'ClientKickEvent',
    ChannelMoveEvent: 'ChannelMoveEvent',
    ClientServerJoinEvent: 'ClientServerJoinEvent',
    ClientChannelLeaveRequest: 'ClientChannelLeaveRequest',
    SectionChangeEvent: 'SectionChangeEvent',
    KickedEvent: 'KickedEvent',
    NoPermissionMessage: 'NoPermissionMessage',
    AuthChallengeRequest: 'AuthChallengeRequest',
    JwtTokenEvent: 'JwtTokenEvent',
    ErrorMessage: 'ErrorMessage',
    ClientChannelJoinEvent: 'ClientChannelJoinEvent',
    ChannelCreateEvent: 'ChannelCreateEvent'
} as const;
export type MessageTypes = typeof MessageTypes[keyof typeof MessageTypes];

