/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageContentDTO { 
    type: MessageContentDTO.TypeEnum;
}
export namespace MessageContentDTO {
    export const TypeEnum = {
        Markdown: 'MARKDOWN'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


