/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Hash } from './hash';


export interface ModelFile { 
    id?: string;
    filename?: string;
    contentType?: string;
    size?: number;
    hash?: Hash;
    created?: string;
}

