/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { MessageDTO } from './messageDTO';
import { SortObject } from './sortObject';


export interface PageMessageDTO { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<MessageDTO>;
    number?: number;
    sort?: SortObject;
    pageable?: PageableObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    empty?: boolean;
}

