/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PeerAnswer { 
    clientTo: string;
    answer: any | null;
    readonly type: PeerAnswer.TypeEnum;
}
export namespace PeerAnswer {
    export const TypeEnum = {
        PeerAnswer: 'PeerAnswer'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


