/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface PeerOffer extends MessageBody { 
    clientTo: string;
    offer: any | null;
    readonly type: PeerOffer.TypeEnum;
}
export namespace PeerOffer {
    export const TypeEnum = {
        PeerOffer: 'PeerOffer'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


