/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface PeerAnswerForward extends MessageBody { 
    clientFrom?: string;
    answer?: any | null;
    readonly type: PeerAnswerForward.TypeEnum;
}
export namespace PeerAnswerForward {
    export const TypeEnum = {
        PeerAnswerForward: 'PeerAnswerForward'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


