/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { JsonNode } from './jsonNode';
import { WebClient } from './webClient';


export interface PeerAnswerForward { 
    clientFrom?: string;
    answer?: JsonNode;
    readonly type: PeerAnswerForward.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace PeerAnswerForward {
    export const TypeEnum = {
        PeerAnswerForward: 'PeerAnswerForward'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


