/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { JsonNode } from './jsonNode';
import { WebClient } from './webClient';


export interface PeerOfferForward { 
    clientFrom?: string;
    offer?: JsonNode;
    readonly type: PeerOfferForward.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace PeerOfferForward {
    export const TypeEnum = {
        PeerOfferForward: 'PeerOfferForward'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


