/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { JsonNode } from './jsonNode';
import { WebClient } from './webClient';


export interface PeerAnswer { 
    clientTo?: string;
    answer?: JsonNode;
    readonly type: PeerAnswer.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace PeerAnswer {
    export const TypeEnum = {
        PeerAnswer: 'PeerAnswer'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


