/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { JsonNode } from './jsonNode';
import { WebClient } from './webClient';


export interface PeerOffer { 
    clientTo?: string;
    offer?: JsonNode;
    readonly type: PeerOffer.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace PeerOffer {
    export const TypeEnum = {
        PeerOffer: 'PeerOffer'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


