/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionDTO { 
    readonly id: string;
    permissions: PermissionDTO.PermissionsEnum[];
    negated: boolean;
    limitedToSection?: string[];
    limitedToChannel?: string[];
}
export namespace PermissionDTO {
    export const PermissionsEnum = {
        Server: 'SERVER',
        ServerJoin: 'SERVER_JOIN',
        ServerEdit: 'SERVER_EDIT',
        ServerEditDescription: 'SERVER_EDIT_DESCRIPTION',
        ServerGroupCreate: 'SERVER_GROUP_CREATE',
        ServerGroupEdit: 'SERVER_GROUP_EDIT',
        ServerGroupDelete: 'SERVER_GROUP_DELETE',
        ServerSectionCreate: 'SERVER_SECTION_CREATE',
        ServerSectionMove: 'SERVER_SECTION_MOVE',
        ServerInvite: 'SERVER_INVITE',
        Section: 'SECTION',
        SectionEdit: 'SECTION_EDIT',
        SectionDelete: 'SECTION_DELETE',
        SectionChannelCreate: 'SECTION_CHANNEL_CREATE',
        SectionChannelOrder: 'SECTION_CHANNEL_ORDER',
        SectionChannelMove: 'SECTION_CHANNEL_MOVE',
        Channel: 'CHANNEL',
        ChannelJoin: 'CHANNEL_JOIN',
        ChannelEdit: 'CHANNEL_EDIT',
        ChannelDelete: 'CHANNEL_DELETE',
        ChannelChat: 'CHANNEL_CHAT',
        ChannelChatWrite: 'CHANNEL_CHAT_WRITE',
        ChannelChatRead: 'CHANNEL_CHAT_READ',
        ChannelUserKick: 'CHANNEL_USER_KICK',
        User: 'USER',
        UserAvatar: 'USER_AVATAR',
        UserBan: 'USER_BAN',
        UserUnban: 'USER_UNBAN',
        UserActivate: 'USER_ACTIVATE',
        UserKick: 'USER_KICK',
        UserGroup: 'USER_GROUP',
        Self: 'SELF',
        SelfAvatar: 'SELF_AVATAR'
    } as const;
    export type PermissionsEnum = typeof PermissionsEnum[keyof typeof PermissionsEnum];
}


