/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionDTO { 
    readonly id: string;
    permissions: Array<PermissionDTO.PermissionsEnum>;
    negated: boolean;
    limitedToSection?: Array<string>;
    limitedToChannel?: Array<string>;
}
export namespace PermissionDTO {
    export const PermissionsEnum = {
        Server: 'SERVER',
        ServerJoin: 'SERVER_JOIN',
        ServerEdit: 'SERVER_EDIT',
        ServerEditDescription: 'SERVER_EDIT_DESCRIPTION',
        ServerEditTitle: 'SERVER_EDIT_TITLE',
        ServerEditIcon: 'SERVER_EDIT_ICON',
        ServerSectionCreate: 'SERVER_SECTION_CREATE',
        ServerUserGroup: 'SERVER_USER_GROUP',
        ServerUserBan: 'SERVER_USER_BAN',
        ServerInvite: 'SERVER_INVITE',
        Section: 'SECTION',
        SectionEdit: 'SECTION_EDIT',
        SectionEditDescription: 'SECTION_EDIT_DESCRIPTION',
        SectionDelete: 'SECTION_DELETE',
        SectionChannelCreate: 'SECTION_CHANNEL_CREATE',
        Channel: 'CHANNEL',
        ChannelJoin: 'CHANNEL_JOIN',
        ChannelEdit: 'CHANNEL_EDIT',
        ChannelEditTitle: 'CHANNEL_EDIT_TITLE',
        ChannelEditDescription: 'CHANNEL_EDIT_DESCRIPTION',
        ChannelEditAvatar: 'CHANNEL_EDIT_AVATAR',
        ChannelDelete: 'CHANNEL_DELETE',
        ChannelUserKick: 'CHANNEL_USER_KICK'
    } as const;
    export type PermissionsEnum = typeof PermissionsEnum[keyof typeof PermissionsEnum];
}


