/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';


export interface PolicyItem { 
    id?: string;
    policies?: Array<Policy>;
}

