/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PreviewFormat = {
    J64: 'J64',
    J256: 'J256',
    J1024: 'J1024'
} as const;
export type PreviewFormat = typeof PreviewFormat[keyof typeof PreviewFormat];

