/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyDTO } from './policyDTO';


export interface RolePolicyDTO extends PolicyDTO { 
    operand: RolePolicyDTO.OperandEnum;
    operator: RolePolicyDTO.OperatorEnum;
    ids: Set<string>;
}
export namespace RolePolicyDTO {
    export const OperandEnum = {
        Group: 'GROUP',
        User: 'USER'
    } as const;
    export type OperandEnum = typeof OperandEnum[keyof typeof OperandEnum];
    export const OperatorEnum = {
        In: 'IN',
        NotIn: 'NOT_IN',
        InAll: 'IN_ALL'
    } as const;
    export type OperatorEnum = typeof OperatorEnum[keyof typeof OperatorEnum];
}


