/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectionExtendedDTO } from './sectionExtendedDTO';
import { MessageBody } from './messageBody';


export interface SectionCreateEvent extends MessageBody { 
    section: SectionExtendedDTO;
    order: number;
    readonly type: SectionCreateEvent.TypeEnum;
}
export namespace SectionCreateEvent {
    export const TypeEnum = {
        SectionCreateEvent: 'SectionCreateEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


