/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectionDTO } from './sectionDTO';
import { MessageBody } from './messageBody';


export interface SectionChangeEvent extends MessageBody { 
    channel: SectionDTO;
    readonly type: SectionChangeEvent.TypeEnum;
}
export namespace SectionChangeEvent {
    export const TypeEnum = {
        SectionChangeEvent: 'SectionChangeEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


