/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface SectionDeleteEvent extends MessageBody { 
    sectionId: string;
    readonly type: SectionDeleteEvent.TypeEnum;
}
export namespace SectionDeleteEvent {
    export const TypeEnum = {
        SectionDeleteEvent: 'SectionDeleteEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


