/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageBody } from './messageBody';


export interface SectionMoveEvent extends MessageBody { 
    sectionId: string;
    order: number;
    readonly type: SectionMoveEvent.TypeEnum;
}
export namespace SectionMoveEvent {
    export const TypeEnum = {
        SectionMoveEvent: 'SectionMoveEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


