/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Edit1Request } from './edit1Request';


export interface ServerDTO { 
    name: string;
    id: string;
    publicKey: { [key: string]: any; };
    description: Array<Edit1Request>;
}

