/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectionDTO } from './sectionDTO';
import { MessageBody } from './messageBody';


export interface ServerTreeChangeMessage extends MessageBody { 
    name: string;
    sections: Array<SectionDTO>;
    readonly type: ServerTreeChangeMessage.TypeEnum;
}
export namespace ServerTreeChangeMessage {
    export const TypeEnum = {
        ServerTreeChangeMessage: 'ServerTreeChangeMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


