/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { SectionDTO } from './sectionDTO';
import { WebClient } from './webClient';


export interface ServerTreeChangeMessage { 
    name: string;
    sections: Array<SectionDTO>;
    readonly type: ServerTreeChangeMessage.TypeEnum;
    server?: Server;
    clients?: Array<WebClient>;
}
export namespace ServerTreeChangeMessage {
    export const TypeEnum = {
        ServerTreeChangeMessage: 'ServerTreeChangeMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


