/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Server } from './server';
import { WebClient } from './webClient';


export interface ServerInfoMessageBody { 
    server?: Server;
    clients?: Array<WebClient>;
    readonly type: ServerInfoMessageBody.TypeEnum;
}
export namespace ServerInfoMessageBody {
    export const TypeEnum = {
        ServerInfoMessageBody: 'ServerInfoMessageBody'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


