/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkdownMessageContentDTO } from './markdownMessageContentDTO';


export interface ServerWriteDTO { 
    name: string;
    description: MarkdownMessageContentDTO;
}

