/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerDTO } from './serverDTO';
import { MessageBody } from './messageBody';


export interface ServerChangeEvent extends MessageBody { 
    server: ServerDTO;
    readonly type: ServerChangeEvent.TypeEnum;
}
export namespace ServerChangeEvent {
    export const TypeEnum = {
        ServerChangeEvent: 'ServerChangeEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


