/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerDTO } from './serverDTO';
import { SectionExtendedDTO } from './sectionExtendedDTO';
import { UserSimpleDTO } from './userSimpleDTO';
import { MessageBody } from './messageBody';


export interface ServerTreeChangeMessage extends MessageBody { 
    server: ServerDTO;
    sections: Array<SectionExtendedDTO>;
    users: Array<UserSimpleDTO>;
    usersNotInChannel: Array<UserSimpleDTO>;
    readonly type: ServerTreeChangeMessage.TypeEnum;
}
export namespace ServerTreeChangeMessage {
    export const TypeEnum = {
        ServerTreeChangeMessage: 'ServerTreeChangeMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


