/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Edit1Request } from './edit1Request';
import { FileDTO } from './fileDTO';


export interface ServerDTO { 
    readonly id: string;
    name: string;
    icon?: FileDTO;
    publicKey: Record<string, any>;
    description: Edit1Request[];
}

