/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupDTO } from './groupDTO';


export interface UserExtendedDTO { 
    id: string;
    publicKey: { [key: string]: any; };
    username: string;
    avatarId?: string;
    groups: Array<GroupDTO>;
    state: UserExtendedDTO.StateEnum;
    knownSince: string;
    lastSeen?: string;
}
export namespace UserExtendedDTO {
    export const StateEnum = {
        PendingAccess: 'PENDING_ACCESS',
        Active: 'ACTIVE',
        Banned: 'BANNED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


