/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';
import { GroupDTO } from './groupDTO';


export interface UserSimpleDTO { 
    id: string;
    publicKey: { [key: string]: any; };
    username: string;
    avatar?: FileDTO;
    groups: Set<GroupDTO>;
}

