/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';
import { GroupDTO } from './groupDTO';


export interface UserExtendedDTO { 
    id: string;
    publicKey: { [key: string]: any; };
    username: string;
    avatar?: FileDTO;
    groups: Array<GroupDTO>;
    state: UserExtendedDTO.StateEnum;
    knownSince: string;
    lastSeen?: string;
}
export namespace UserExtendedDTO {
    export const StateEnum = {
        InvitationPending: 'INVITATION_PENDING',
        Blocked: 'BLOCKED',
        Allowed: 'ALLOWED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


