/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';


export interface UserExtendedDTO { 
    id: string;
    publicKey: any | null;
    username: string;
    avatar?: FileDTO;
    state: UserExtendedDTO.StateEnum;
    knownSince: string;
    lastSeen?: string;
}
export namespace UserExtendedDTO {
    export const StateEnum = {
        InvitationPending: 'INVITATION_PENDING',
        Blocked: 'BLOCKED',
        Allowed: 'ALLOWED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


