export * from './channelController.service';
import { ChannelControllerService } from './channelController.service';
export * from './chatController.service';
import { ChatControllerService } from './chatController.service';
export * from './groupController.service';
import { GroupControllerService } from './groupController.service';
export * from './infoController.service';
import { InfoControllerService } from './infoController.service';
export * from './policyController.service';
import { PolicyControllerService } from './policyController.service';
export * from './sectionController.service';
import { SectionControllerService } from './sectionController.service';
export * from './serverController.service';
import { ServerControllerService } from './serverController.service';
export * from './todoController.service';
import { TodoControllerService } from './todoController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [ChannelControllerService, ChatControllerService, GroupControllerService, InfoControllerService, PolicyControllerService, SectionControllerService, ServerControllerService, TodoControllerService, UserControllerService];
