export * from './channelController.service';
import { ChannelControllerService } from './channelController.service';
export * from './chatController.service';
import { ChatControllerService } from './chatController.service';
export * from './infoController.service';
import { InfoControllerService } from './infoController.service';
export * from './sectionController.service';
import { SectionControllerService } from './sectionController.service';
export * from './serverController.service';
import { ServerControllerService } from './serverController.service';
export * from './todoController.service';
import { TodoControllerService } from './todoController.service';
export const APIS = [ChannelControllerService, ChatControllerService, InfoControllerService, SectionControllerService, ServerControllerService, TodoControllerService];
