/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignedContent } from './signedContent';


export interface AuthChallengeResponse { 
    publicKey: { [key: string]: object; };
    challenge: SignedContent;
    username: string;
    readonly type: AuthChallengeResponse.TypeEnum;
}
export namespace AuthChallengeResponse {
    export const TypeEnum = {
        AuthChallengeResponse: 'AuthChallengeResponse'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


