/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelDTO } from './channelDTO';


export interface ChannelCreateEvent { 
    sectionId: string;
    order: number;
    channel: ChannelDTO;
    readonly type: ChannelCreateEvent.TypeEnum;
}
export namespace ChannelCreateEvent {
    export const TypeEnum = {
        ChannelCreateEvent: 'ChannelCreateEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


