/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChannelMoveEvent { 
    channelId: string;
    order: number;
    sectionId?: string;
    readonly type: ChannelMoveEvent.TypeEnum;
}
export namespace ChannelMoveEvent {
    export const TypeEnum = {
        ChannelMoveEvent: 'ChannelMoveEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


