/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientServerLeaveEvent { 
    userId: string;
    readonly type: ClientServerLeaveEvent.TypeEnum;
}
export namespace ClientServerLeaveEvent {
    export const TypeEnum = {
        ClientServerLeaveEvent: 'ClientServerLeaveEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


