/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorMessage { 
    message?: string;
    readonly type: ErrorMessage.TypeEnum;
}
export namespace ErrorMessage {
    export const TypeEnum = {
        ErrorMessage: 'ErrorMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


