/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HashDTO } from './hashDTO';


export interface FileDTO { 
    id: string;
    filename: string;
    contentType: string;
    hash: HashDTO;
    created: string;
    size: number;
}

