/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HashDTO { 
    type: HashDTO.TypeEnum;
    hash: string;
}
export namespace HashDTO {
    export const TypeEnum = {
        Sha256: 'SHA_256'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


