/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IceServer } from './iceServer';


export interface IceServerMessage { 
    iceServers: Array<IceServer>;
    readonly type: IceServerMessage.TypeEnum;
}
export namespace IceServerMessage {
    export const TypeEnum = {
        IceServerMessage: 'IceServerMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


