/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KickRequestDTO { 
    reason?: KickRequestDTO.ReasonEnum;
    message?: string;
}
export namespace KickRequestDTO {
    export const ReasonEnum = {
        AlreadyConnected: 'ALREADY_CONNECTED',
        UnauthorizedRequest: 'UNAUTHORIZED_REQUEST',
        InternalError: 'INTERNAL_ERROR',
        Banned: 'BANNED',
        Other: 'OTHER'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
}


