/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageDeleteEvent { 
    id: string;
    readonly type: MessageDeleteEvent.TypeEnum;
}
export namespace MessageDeleteEvent {
    export const TypeEnum = {
        MessageDeleteEvent: 'MessageDeleteEvent'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


