/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PeerOfferForward { 
    clientFrom: string;
    offer: any | null;
    readonly type: PeerOfferForward.TypeEnum;
}
export namespace PeerOfferForward {
    export const TypeEnum = {
        PeerOfferForward: 'PeerOfferForward'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


