/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelExtendedDTO } from './channelExtendedDTO';


export interface SectionExtendedDTO { 
    name: string;
    id: string;
    channels: Array<ChannelExtendedDTO>;
}

