/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkdownMessageContentDTO } from './markdownMessageContentDTO';
import { FileDTO } from './fileDTO';
import { FileMessageContentDTO } from './fileMessageContentDTO';


/**
 * @type ServerDTODescriptionInner
 * @export
 */
export type ServerDTODescriptionInner = FileMessageContentDTO | MarkdownMessageContentDTO;

