/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';
import { ServerDTODescriptionInner } from './serverDTODescriptionInner';


export interface ServerDTO { 
    readonly id: string;
    name: string;
    icon?: FileDTO;
    publicKey: { [key: string]: any; };
    description: Array<ServerDTODescriptionInner>;
}

