/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SortObject { 
    empty?: boolean;
    sorted?: boolean;
    unsorted?: boolean;
}

