/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (http://openapi-generator.tech).
 * http://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrackMetadataMessage { 
    mid: string;
    label: TrackMetadataMessage.LabelEnum;
    readonly type: TrackMetadataMessage.TypeEnum;
}
export namespace TrackMetadataMessage {
    export const LabelEnum = {
        Cameramic: 'CAMERAMIC',
        Screen: 'SCREEN'
    } as const;
    export type LabelEnum = typeof LabelEnum[keyof typeof LabelEnum];
    export const TypeEnum = {
        TrackMetadataMessage: 'TrackMetadataMessage'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


